### PR TITLE
Primes

### PR DESCRIPTION
**Pull request by AngelEzquerra**
This PR adds a few prime related functions:

- primes: Generate prime values up to a number
- factor: Factorize a number
- isprime: Check if a number (or a tensor element-wise) is prime

These can be used in a number of digital communications and cryptography related algorithms.

### CODE REVIEW

**Comment by mratsim** [comment]
This should be in a number-theory repo I think?

**Comment by AngelEzquerra** [comment]
> This should be in a number-theory repo I think?

Prime number generation and checking are quite common in signal processing and digital communications. For example, primes are used to generate sequences such as Zadoff-Chu which are used in all sorts of context in 5G cellular systems (e.g. to generate sync and reference signals, random access and to transmit control information).

I agree that these could perhaps be put in a separate repo, along with procedures to generate bessel functions, etc., but then impulse would end up having to reference that separate repo (e.g. bessel functions are required to the Kaiser filter windows that I added in the other PR I recently sent: https://github.com/SciNim/impulse/pull/6). So, for now, I would just keep them all in impulse (which is still kind of empty anyway) as I don't intend to add many more of these beyond what's strictly needed to add more signal processing capabilities to impulse. If these grow much beyond that scope, we could split them up into their own repo later.

What do you think?

**Comment by Vindaar** [comment]
We have the https://github.com/SciNim/scinim repo, which could be another alternative. In general though in the current Nim landscape I think fewer, but larger repos are better than many tiny ones for discoverability.

**Comment by AngelEzquerra** [comment]
I just made https://github.com/SciNim/scinim/pull/16 to add this code to the scinim repo rather than to impulse.

**Comment by Vindaar** [comment]
As it's part of `scinim` now, closing this.

**Pull request closed without merging**
