### PR TITLE
Signal

### PR DESCRIPTION
**Pull request by AngelEzquerra**
This adds a signal processing related module, starting with a kaiser window and a firls FIR design function.

### CODE REVIEW

**Comment by Vindaar** [comment]
For the Windows CI we need to install BLAS / LAPACK. Should be an easy extension of the CI YAML file. In ggplotnim I do it like this:

https://github.com/Vindaar/ggplotnim/blob/master/.github/workflows/ci.yml#L57-L71

We'll probably want to switch away from setup-nim soon, too. It hasn't been updated in a long time and I think at this point there are better ways to build / get Nim (for the OSX failure).

**Comment by Vindaar** [comment]
Otherwise looking good, as far as my code review can judge (i.e. haven't tried to check the implementation does what it says it does :grin:). Only wondered if there's some refactoring that could be done to share more code between the symmetric / non symmetric branches in `firls`. There seems to be a lot of similarity in the for loop code. But I don't mind either way.

**Comment by AngelEzquerra** [comment]
> Otherwise looking good, as far as my code review can judge (i.e. haven't tried to check the implementation does what it says it does 😁). Only wondered if there's some refactoring that could be done to share more code between the symmetric / non symmetric branches in `firls`. There seems to be a lot of similarity in the for loop code. But I don't mind either way.

I'd be OK trying to unify the code a bit because as you said it both branches are quite similar. However, the differences are large enough that it might be a bit complicated, I'd have to give it a try.
If you don't mind, I'd rather add this as is, and then I can try to improve it later?

**Comment by Vindaar** [comment]
Will you add the BLAS / LAPACK dependcny for Windows into the CI file? Fixing OSX can be done at a later time. Once I look into it, I need to do it for a variety of repositories anyway.

**Comment by Vindaar** [comment]
Merging despite the CI issues. They are not very relevant imo for the time being.

**Pull request merged**
